name: Lints

on:
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Maggi64/eslint-plus-action@master
        with:
          includeGlob: 'src/**/*'
          npmInstall: true
